# Generated by Django 4.2.2 on 2023-06-27 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=100)),
                ('email_content', models.TextField(max_length=1000)),
                ('sent_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
